### ISSUE TITLE
Turn off the min / max 

### ISSUE THREAD

**Issue by doodahdayz** [mobile-simformsolutions/SSStepper#8]
It would be nice if there was a way to disable the vertical up and down on the control.  The inability to turn off that makes this control useless when in a scrollview.

**Comment by shubham4901** [comment]
Hello @doodahdayz!
Thank you for using Simform OpenSource.
Now in new Version 1.0.1.
You can customize the vertical scroll and enable/disable vertical scroll as per your needs.
